[package]
name = "softaes"
version = "0.1.7"
edition = "2021"
categories = ["no-std", "cryptography", "wasm"]
keywords = ["aes", "aes-round", "software", "no-std", "cryptography"]
license = "MIT"
homepage = "https://github.com/jedisct1/rust-softaes"
repository = "https://github.com/jedisct1/rust-softaes"
authors = ["Frank Denis <github@pureftpd.org>"]
description = "Software AES round functions and key scheduling in pure Rust, with no_std support and no hardware AES requirement"
include = ["src/**/*.rs", "tests/**/*.rs", "benches/**/*.rs", "LICENSE"]

[[bench]]
name = "rounds"
harness = false
